// <auto-generated />
using System;
using EventService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventService.Migrations
{
    [DbContext(typeof(EventDbContext))]
    [Migration("20250522065512_SeedRealEvents")]
    partial class SeedRealEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventService.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d"),
                            Description = "Live music concert by Coldplay",
                            EndTime = new DateTime(2025, 7, 15, 23, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Coldplay World Tour",
                            StartTime = new DateTime(2025, 7, 15, 20, 0, 0, 0, DateTimeKind.Utc),
                            VenueId = new Guid("d6c5b4a3-f2e1-a0b9-c8d7-e6f5a4b3c2d1")
                        },
                        new
                        {
                            Id = new Guid("2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e"),
                            Description = "Google's annual developer conference",
                            EndTime = new DateTime(2025, 5, 14, 17, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Google I/O 2025",
                            StartTime = new DateTime(2025, 5, 14, 10, 0, 0, 0, DateTimeKind.Utc),
                            VenueId = new Guid("e7d6c5b4-a3f2-e1d0-c9b8-a7f6e5d4c3b2")
                        },
                        new
                        {
                            Id = new Guid("3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f"),
                            Description = "Annual fan convention for comics and pop culture",
                            EndTime = new DateTime(2025, 7, 21, 18, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Comic-Con International",
                            StartTime = new DateTime(2025, 7, 18, 9, 0, 0, 0, DateTimeKind.Utc),
                            VenueId = new Guid("f8e7d6c5-b4a3-f2e1-d0c9-b8a7f6e5d4c3")
                        },
                        new
                        {
                            Id = new Guid("4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a"),
                            Description = "Final game of the NBA Championship",
                            EndTime = new DateTime(2025, 6, 20, 23, 30, 0, 0, DateTimeKind.Utc),
                            Name = "NBA Finals Game 7",
                            StartTime = new DateTime(2025, 6, 20, 20, 30, 0, 0, DateTimeKind.Utc),
                            VenueId = new Guid("09f8e7d6-c5b4-a3f2-e1d0-c9b8a7f6e5d4")
                        },
                        new
                        {
                            Id = new Guid("5e6f7a8b-9c0d-1e2f-3a4b-5c6d7e8f9a0b"),
                            Description = "Technology, Entertainment, and Design conference",
                            EndTime = new DateTime(2025, 4, 10, 17, 0, 0, 0, DateTimeKind.Utc),
                            Name = "TED Global 2025",
                            StartTime = new DateTime(2025, 4, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            VenueId = new Guid("1a09f8e7-d6c5-b4a3-f2e1-d0c9b8a7f6e5")
                        },
                        new
                        {
                            Id = new Guid("6f7a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c"),
                            Description = "Electronic dance music festival",
                            EndTime = new DateTime(2025, 7, 28, 2, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tomorrowland",
                            StartTime = new DateTime(2025, 7, 26, 16, 0, 0, 0, DateTimeKind.Utc),
                            VenueId = new Guid("2b1a09f8-e7d6-c5b4-a3f2-e1d0c9b8a7f6")
                        },
                        new
                        {
                            Id = new Guid("7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d"),
                            Description = "Apple Worldwide Developers Conference",
                            EndTime = new DateTime(2025, 6, 3, 17, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Apple WWDC 2025",
                            StartTime = new DateTime(2025, 6, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            VenueId = new Guid("3c2b1a09-f8e7-d6c5-b4a3-f2e1d0c9b8a7")
                        },
                        new
                        {
                            Id = new Guid("8b9c0d1e-2f3a-4b5c-6d7e-8f9a0b1c2d3e"),
                            Description = "Kickoff for the Summer Olympics",
                            EndTime = new DateTime(2025, 7, 24, 23, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Olympic Games Opening Ceremony",
                            StartTime = new DateTime(2025, 7, 24, 20, 0, 0, 0, DateTimeKind.Utc),
                            VenueId = new Guid("4d3c2b1a-09f8-e7d6-c5b4-a3f2e1d0c9b8")
                        },
                        new
                        {
                            Id = new Guid("9c0d1e2f-3a4b-5c6d-7e8f-9a0b1c2d3e4f"),
                            Description = "Final match of the FIFA World Cup",
                            EndTime = new DateTime(2025, 12, 18, 21, 0, 0, 0, DateTimeKind.Utc),
                            Name = "FIFA World Cup Final",
                            StartTime = new DateTime(2025, 12, 18, 18, 0, 0, 0, DateTimeKind.Utc),
                            VenueId = new Guid("5e4d3c2b-1a09-f8e7-d6c5-b4a3f2e1d0c9")
                        },
                        new
                        {
                            Id = new Guid("0d1e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a"),
                            Description = "Consumer Electronics Show",
                            EndTime = new DateTime(2025, 1, 10, 18, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CES 2025",
                            StartTime = new DateTime(2025, 1, 7, 10, 0, 0, 0, DateTimeKind.Utc),
                            VenueId = new Guid("6f5e4d3c-2b1a-09f8-e7d6-c5b4a3f2e1d0")
                        });
                });

            modelBuilder.Entity("EventService.Entities.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumSeat")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6c5b4a3-f2e1-a0b9-c8d7-e6f5a4b3c2d1"),
                            EventId = new Guid("1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d"),
                            Location = "London, UK",
                            Name = "Wembley Stadium",
                            NumSeat = 50
                        },
                        new
                        {
                            Id = new Guid("e7d6c5b4-a3f2-e1d0-c9b8-a7f6e5d4c3b2"),
                            EventId = new Guid("2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e"),
                            Location = "Mountain View, CA",
                            Name = "Shoreline Amphitheatre",
                            NumSeat = 100
                        },
                        new
                        {
                            Id = new Guid("f8e7d6c5-b4a3-f2e1-d0c9-b8a7f6e5d4c3"),
                            EventId = new Guid("3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f"),
                            Location = "San Diego, CA",
                            Name = "San Diego Convention Center",
                            NumSeat = 150
                        },
                        new
                        {
                            Id = new Guid("09f8e7d6-c5b4-a3f2-e1d0-c9b8a7f6e5d4"),
                            EventId = new Guid("4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a"),
                            Location = "Boston, MA",
                            Name = "TD Garden",
                            NumSeat = 60
                        },
                        new
                        {
                            Id = new Guid("1a09f8e7-d6c5-b4a3-f2e1-d0c9b8a7f6e5"),
                            EventId = new Guid("5e6f7a8b-9c0d-1e2f-3a4b-5c6d7e8f9a0b"),
                            Location = "Vancouver, Canada",
                            Name = "Vancouver Convention Centre",
                            NumSeat = 70
                        },
                        new
                        {
                            Id = new Guid("2b1a09f8-e7d6-c5b4-a3f2-e1d0c9b8a7f6"),
                            EventId = new Guid("6f7a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c"),
                            Location = "Boom, Belgium",
                            Name = "Boom Recreation Area",
                            NumSeat = 50
                        },
                        new
                        {
                            Id = new Guid("3c2b1a09-f8e7-d6c5-b4a3-f2e1d0c9b8a7"),
                            EventId = new Guid("7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d"),
                            Location = "Cupertino, CA",
                            Name = "Apple Park",
                            NumSeat = 80
                        },
                        new
                        {
                            Id = new Guid("4d3c2b1a-09f8-e7d6-c5b4-a3f2e1d0c9b8"),
                            EventId = new Guid("8b9c0d1e-2f3a-4b5c-6d7e-8f9a0b1c2d3e"),
                            Location = "Paris, France",
                            Name = "Stade de France",
                            NumSeat = 10
                        },
                        new
                        {
                            Id = new Guid("5e4d3c2b-1a09-f8e7-d6c5-b4a3f2e1d0c9"),
                            EventId = new Guid("9c0d1e2f-3a4b-5c6d-7e8f-9a0b1c2d3e4f"),
                            Location = "Lusail, Qatar",
                            Name = "Lusail Stadium",
                            NumSeat = 50
                        },
                        new
                        {
                            Id = new Guid("6f5e4d3c-2b1a-09f8-e7d6-c5b4a3f2e1d0"),
                            EventId = new Guid("0d1e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a"),
                            Location = "Las Vegas, NV",
                            Name = "Las Vegas Convention Center",
                            NumSeat = 1000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
